version: '3.1'

services:
  db:
    image: mysql:8.4
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
